spring.jpa.hibernate.ddl-auto: update

server:
  port: 8082
spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:15432/application
    username: application
    password: 12345678

    testWhileIdle: true
    validationQuery: SELECT 1

  application:
    name: application-service

security:
  jwt:
    token:
      secret-key: chave_microservices

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}

  instance:
    prefer-ip-address: true