version: '3.3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: application
      POSTGRES_DB: application
    ports:
      - "15432:5432"
    volumes:
      - /usr/local/dados/PostgreSQL-application-service:/var/lib/postgresql/data
