server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka/}
  instance:
    prefer-ip-address: true

zuul:
  ignored-services: '*'
  prefix: /api

  routes:
    auth:
      path: /auth/**
      service-id: auth
      strip-prefix: false
      custom-sensitive-headers: true

    application:
      path: /application/**
      service-id: application-service
      strip-prefix: false
      custom-sensitive-headers: true

    logger:
      path: /logger/**
      serviceId: dblogger-service
      strip-prefix: false
      custom-sensitive-headers: true
