version: '3.3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: auth
      POSTGRES_DB: auth
    ports:
      - "5332:5432"
    volumes:
      - /usr/local/dados/PostgreSQL-auth-service:/var/lib/postgresql/data
