server:
  port: 8888

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
        server:
          git:
            uri: https://github.com/alexsandrodesenvolvedor/config-server
            #propriedade para definir a branch. Se não informar vai buscar na branch master
            default-label: main

